name: 'Terraform S3 Pipeline'

on:
  push:
    branches:
    - flugel-branch
  pull_request: 
    branches:
    - flugel-branch

jobs:
  terraform:
    name: 'Terraform-S3-Bucket'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: v1.1.4
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args: '-var="env=dev"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
